DemoFirmaMitEntityFramework/DemoFirmaMitEntityFramework/Models/Angestellte.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DemoFirmaMitEntityFramework.Models
{
    public class Angestellte
    {
        [Key]
        public int MitarbeiterID { get; set; }
        [Required,StringLength(50)]
        public string Vorname { get; set; }
        [Required,StringLength(50)]
        public string Nachname { get; set; }
    }
}

DemoFirmaMitEntityFramework/DemoFirmaMitEntityFramework/Models/ErrorViewModel.cs
using System;

namespace DemoFirmaMitEntityFramework.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DemoFirmaMitEntityFramework/DemoFirmaMitEntityFramework/Controllers/AngestelltesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DemoFirmaMitEntityFramework.Data;
using DemoFirmaMitEntityFramework.Models;

namespace DemoFirmaMitEntityFramework.Controllers
{
    public class AngestelltesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AngestelltesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Angestelltes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Mitarbeiter.ToListAsync());
        }

        // GET: Angestelltes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var angestellte = await _context.Mitarbeiter
                .FirstOrDefaultAsync(m => m.MitarbeiterID == id);
            if (angestellte == null)
            {
                return NotFound();
            }

            return View(angestellte);
        }

        // GET: Angestelltes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Angestelltes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MitarbeiterID,Vorname,Nachname")] Angestellte angestellte)
        {
            if (ModelState.IsValid)
            {
                _context.Add(angestellte);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(angestellte);
        }

        // GET: Angestelltes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var angestellte = await _context.Mitarbeiter.FindAsync(id);
            if (angestellte == null)
            {
                return NotFound();
            }
            return View(angestellte);
        }

        // POST: Angestelltes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MitarbeiterID,Vorname,Nachname")] Angestellte angestellte)
        {
            if (id != angestellte.MitarbeiterID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(angestellte);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AngestellteExists(angestellte.MitarbeiterID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(angestellte);
        }

        // GET: Angestelltes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var angestellte = await _context.Mitarbeiter
                .FirstOrDefaultAsync(m => m.MitarbeiterID == id);
            if (angestellte == null)
            {
                return NotFound();
            }

            return View(angestellte);
        }

        // POST: Angestelltes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var angestellte = await _context.Mitarbeiter.FindAsync(id);
            _context.Mitarbeiter.Remove(angestellte);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AngestellteExists(int id)
        {
            return _context.Mitarbeiter.Any(e => e.MitarbeiterID == id);
        }
    }
}

DemoFirmaMitEntityFramework/DemoFirmaMitEntityFramework/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DemoFirmaMitEntityFramework.Models;

namespace DemoFirmaMitEntityFramework.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DemoFirmaMitEntityFramework/DemoFirmaMitEntityFramework/Views/Angestelltes/Create.cshtml
@model DemoFirmaMitEntityFramework.Models.Angestellte

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Angestellte</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Vorname" class="control-label"></label>
                <input asp-for="Vorname" class="form-control" />
                <span asp-validation-for="Vorname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nachname" class="control-label"></label>
                <input asp-for="Nachname" class="form-control" />
                <span asp-validation-for="Nachname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DemoFirmaMitEntityFramework/DemoFirmaMitEntityFramework/Views/Angestelltes/Delete.cshtml
@model DemoFirmaMitEntityFramework.Models.Angestellte

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Angestellte</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vorname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vorname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nachname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nachname)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MitarbeiterID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DemoFirmaMitEntityFramework/DemoFirmaMitEntityFramework/Views/Angestelltes/Details.cshtml
@model DemoFirmaMitEntityFramework.Models.Angestellte

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Angestellte</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vorname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vorname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nachname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nachname)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.MitarbeiterID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DemoFirmaMitEntityFramework/DemoFirmaMitEntityFramework/Views/Angestelltes/Edit.cshtml
@model DemoFirmaMitEntityFramework.Models.Angestellte

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Angestellte</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MitarbeiterID" />
            <div class="form-group">
                <label asp-for="Vorname" class="control-label"></label>
                <input asp-for="Vorname" class="form-control" />
                <span asp-validation-for="Vorname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nachname" class="control-label"></label>
                <input asp-for="Nachname" class="form-control" />
                <span asp-validation-for="Nachname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DemoFirmaMitEntityFramework/DemoFirmaMitEntityFramework/Views/Angestelltes/Index.cshtml
@model IEnumerable<DemoFirmaMitEntityFramework.Models.Angestellte>

@{
    ViewData["Title"] = "Index";
}

<h1>Hier ist die Liste aller Mitarbeiter</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Vorname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nachname)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Vorname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nachname)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.MitarbeiterID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.MitarbeiterID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.MitarbeiterID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

DemoFirmaMitEntityFramework/DemoFirmaMitEntityFramework/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Willkommen!</h1>
    <p>Hier mal eine kleine Demo von der Nutzung von ASP.net core MVC mit Entity Framework in Verbindung mit einer MSSQL Datenbank.</p>
</div>

DemoFirmaMitEntityFramework/DemoFirmaMitEntityFramework/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoFirmaMitEntityFramework</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoFirmaMitEntityFramework</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Angestelltes" asp-action="Index">Mitarbeiterliste</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - DemoFirmaMitEntityFramework - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>